theme: jekyll-theme-slate
title: ubnqf's home page
<meta name="twitter:title" content="test用HP" />
<meta name="twitter:description" content="リンクプレビューの表示テスト w/ twitter cards" />
<meta property="og:title" content="test用HP" />
<meta property="og:description" content="リンクプレビューの表示テスト w/ open graph" />
